title: Elaine Gorom
description: Applied Mathematician | Technical Problem Solver
url: "https://elainegorom.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

theme: null

permalink: /blog/:title/

collections:
  projects:
    output: true
